### ISSUE TITLE
Self-managed hosting

### ISSUE THREAD

**Issue by ryanhiebert** [ehmatthes/django-simple-deploy#343]
Hear me out, this is a little wild and a complete paradigm breakdown for me. I'm trying to figure out whether it should have some relationship to django-simple-deploy to allow for a better transition to a more traditional controlled approach to deployment.

One killer feature of Wordpress is that it can **update itself**, you can **install plugins from a store**, and **modify just about everything** about it. As a developer this makes me cringe for all kinds of reasons, but it's also an incredible way to get people that don't know about development to run something themselves. A great on-ramp. It's got significant drawbacks, but I'm so interested in exploring possibilities for making getting started with Django development simpler that I'm really interested to see what could happen.

I haven't figured out exactly what that looks like yet. Perhaps a docker image running systemd to manage the application, and then some fancy footwork with virtualenvs to allow for installing new sets of dependencies through a web UI without making the upgrade irreversible.

While I want this so that it makes it simpler for people to get started with Django, I really don't want it to stop there. I want little places where people can start by doing CMS-style stuff for a while, hit a limitation, then dip their toes into some code to make something custom, all in the UI. Their first taste of development. As they experience that, then somewhere along the way I want it be easy to switch from a non-developer focused approach to a more traditional approach with git, reproducible docker images, even up to and including putting it on a PaaS.

For now I'm just playing around with this idea, but I wonder if you have any thoughts about it given this project and what you're trying to do with it: simplify the deployment on-ramp. It seems like perhaps an good ramp from the self-mutating approach to a more traditional deployment model might fit really well with using this project. Does that sound right? Do you see problems or things that I should keep in mind as I'm thinking about this if I want to use django-simple-deploy to create that pathway for project progression?

I don't immediately see this as reasonable to make a platform *of* this project, it's really a totally different approach afaict, but if there are things that I can do to make the transition simpler as a new person transitions to be a developer, that would be really cool.

**Comment by ehmatthes** [comment]
Hi Ryan. I've always found that this project brings up interesting ideas once you start thinking about it more. At first it seems like it's just focused on beginners, but it has use cases for people at all experience levels, and all kinds of reasons for using Django.

> One killer feature of Wordpress is that it can update itself, you can install plugins from a store, and modify just about everything about it. As a developer this makes me cringe for all kinds of reasons, but it's also an incredible way to get people that don't know about development to run something themselves. A great on-ramp. It's got significant drawbacks, but I'm so interested in exploring possibilities for making getting started with Django development simpler that I'm really interested to see what could happen.

I think there's a compelling use case for defining simpler ways of starting projects with Django, that lead naturally into a fully-fledged Django project. That's why I'm excited about projects like [nanodjango](https://github.com/radiac/nanodjango), which take the single-file approach that's been discussed among insiders for years now, but also give a straightforward path for converting your project into a standard Django project as it evolves.

That said, I'm not so convinced of trying to turn Django into something that's trying to serve non-programmers as well as developers. I can see some third-party projects using Django under the hood to do something like this, but I don't know how much it matters that Django is being used to build out the wrapper platform. Is Wagtail doing some of what you're describing?

> While I want this so that it makes it simpler for people to get started with Django, I really don't want it to stop there. I want little places where people can start by doing CMS-style stuff for a while, hit a limitation, then dip their toes into some code to make something custom, all in the UI.

This reminds me of Anvil.

> For now I'm just playing around with this idea, but I wonder if you have any thoughts about it given this project and what you're trying to do with it: simplify the deployment on-ramp. It seems like perhaps a good ramp from the self-mutating approach to a more traditional deployment model might fit really well with using this project.

As simple_deploy gets out of the pre-1.0 proof-of-concept phase and gains some stability, one of the things I'm most curious to see is where its boundaries are. What kinds of projects are "simple" enough for it to be relevant? How complex of a project can it handle, while staying true to the original vision of not trying to handle overly complex cases? I think the plugin model really opens up those possibilities. You can have some plugins that handle the simplest use cases, but there's not much stopping someone from writing a much more complex plugin, I believe.

The main thing I'm trying to do right now is be really clear about what tools simple_deploy offers to plugins. For example it has utilities like `add_file()`, `add_dir()`, and `modify_file()`. Those are all tasks a plugin needs to carry out in order to prepare a project for deployment. If there are capabilities you'd like to see to support a specific aspect of your vision, please feel free to propose them, or even just discuss ideas.
