### ISSUE TITLE
Could not provision Azure resources in westus2

### ISSUE THREAD

**Issue by iamjameswalters** [ehmatthes/django-simple-deploy#60]
When attempting an Azure deployment, I came across this issue:

```
Creating Azure F1 plan...
This region has quota of 0 instances for your subscription. Try selecting different region or SKU.
```
Likewise, for the database:
```
Creating PostgreSQL Server 'sd-pg-server-Khuh1c6nw49PYRYY' in group 'SimpleDeployGroup'...
This subscription is restricted from provisioning PostgreSQL servers in this region. Please choose a different region or open a support request with service and subscription limits (quotas) issue type.
```

**Comment by ehmatthes** [comment]
I have run into this issue a number of times while testing. That's why I started testing on a fairly high level paid plan, much higher than I'd use for a low to moderate traffic app. For test runs that last just a few minutes, these are negligible cost, and they're almost always available.

The command that's causing this issue is [here](https://github.com/ehmatthes/django-simple-deploy/blob/main/simple_deploy/management/commands/utils/deploy_azure.py#L358), and the documentation for [appservice](https://docs.microsoft.com/en-us/cli/azure/appservice?view=azure-cli-latest) includes the command [appservice list-locations](https://docs.microsoft.com/en-us/cli/azure/appservice?view=azure-cli-latest#az-appservice-list-locations). The command `az appservice list-locations --sku F1 --output table` shows locations that support the F1 sku, but that doesn't say anything about whether those locations have currently exceeded quota or not. I'm not sure how to filter the list to show only locations that currently have plans available at the F1 level. I should probably add a cli arg to allow specifying a different region for Azure deployments.

**Comment by ehmatthes** [comment]
Closing; see #83.

**Comment by ehmatthes** [comment]
I'm sorry to add that comment without explaining a bit further; I thought I had opened this issue.

In order to focus development of django-simple-deploy, I am removing support for Azure for the time being. There are much better platforms for the pre-1.0 phase of this project.

I hope this doesn't impact your work significantly. If it does and you'd like to help develop a robust approach to supporting Azure, I'd be happy to discuss that. I'm going to close this issue, but feel free to reopen it or open a separate issue.

**Comment by iamjameswalters** [comment]
No worries! I completely understand. I just filed this because I wanted to help the project along, I've never been able to make sense of Azure. The difficulties incumbent here are worth pivoting to other platforms in the meantime, though I'd love to see an Azure deployment option worked out someday.
